//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MINTLoader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MINTLoader.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from MINT.
        /// </summary>
        internal static string MenuOpenMINT {
            get {
                return ResourceManager.GetString("MenuOpenMINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected study is not available on the MINT server..
        /// </summary>
        internal static string MessageCannotOpenNonStreamingStudy {
            get {
                return ResourceManager.GetString("MessageCannotOpenNonStreamingStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of the selected studies are not on the MINT server..
        /// </summary>
        internal static string MessageFormatXNonStreamingStudiesCannotBeOpened {
            get {
                return ResourceManager.GetString("MessageFormatXNonStreamingStudiesCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the selected studies is not on the MINT server..
        /// </summary>
        internal static string MessageOneNonStreamingStudyCannotBeOpened {
            get {
                return ResourceManager.GetString("MessageOneNonStreamingStudyCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to view a study is denied..
        /// </summary>
        internal static string MessageOpenStudyPermissionDenied {
            get {
                return ResourceManager.GetString("MessageOpenStudyPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from MINT.
        /// </summary>
        internal static string ToolbarOpenMINT {
            get {
                return ResourceManager.GetString("ToolbarOpenMINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open study from Medical Imaging Network Transfer (MINT) service.
        /// </summary>
        internal static string TooltipOpenMINT {
            get {
                return ResourceManager.GetString("TooltipOpenMINT", resourceCulture);
            }
        }
    }
}
